global_params:
  working_dir: cache
  graph_backend: kuzu # graph database backend, support: kuzu, networkx
  kv_backend: rocksdb # key-value store backend, support: rocksdb, json_kv

nodes:
  - id: read_files # id is unique in the pipeline, and can be referenced by other steps
    op_name: read
    type: source
    dependencies: []
    params:
        input_path:
          - examples/input_examples/jsonl_demo.jsonl # input file path, support json, jsonl, txt, pdf. See examples/input_examples for examples

  - id: chunk_documents
    op_name: chunk
    type: map_batch
    dependencies:
      - read_files
    execution_params:
      replicas: 4
    params:
        chunk_size: 1024 # chunk size for text splitting
        chunk_overlap: 100 # chunk overlap for text splitting

  - id: build_kg
    op_name: build_kg
    type: map_batch
    dependencies:
      - chunk_documents
    execution_params:
      replicas: 1
      batch_size: 128

  - id: quiz
    op_name: quiz
    type: map_batch
    dependencies:
      - build_kg
    execution_params:
      replicas: 1
      batch_size: 128
    params:
      quiz_samples: 2 # number of quiz samples to generate

  - id: judge
    op_name: judge
    type: map_batch
    dependencies:
      - quiz
    execution_params:
      replicas: 1
      batch_size: 128

  - id: partition
    op_name: partition
    type: aggregate
    dependencies:
      - judge
    params:
      method: ece # ece is a custom partition method based on comprehension loss
      method_params:
        max_units_per_community: 20 # max nodes and edges per community
        min_units_per_community: 5 # min nodes and edges per community
        max_tokens_per_community: 10240 # max tokens per community
        unit_sampling: max_loss # unit sampling strategy, support: random, max_loss, min_loss

  - id: generate
    op_name: generate
    type: map_batch
    dependencies:
      - partition
    execution_params:
      replicas: 1
      batch_size: 128
    save_output: true # save output
    params:
      method: fill_in_blank
      num_of_questions: 5
      data_format: Alpaca # Alpaca, Sharegpt, ChatML
