global_params:
  working_dir: cache
  graph_backend: networkx # graph database backend, support: kuzu, networkx
  kv_backend: json_kv # key-value store backend, support: rocksdb, json_kv

nodes:
  - id: read
    op_name: read
    type: source
    dependencies: []
    params:
      input_path:
        - examples/input_examples/jsonl_demo.jsonl

  - id: chunk
    op_name: chunk
    type: map_batch
    dependencies:
      - read
    execution_params:
      replicas: 4
    params:
      chunk_size: 20480 # larger chunk size for better context
      chunk_overlap: 2000

  - id: build_kg
    op_name: build_kg
    type: map_batch
    dependencies:
      - chunk
    execution_params:
      replicas: 1
      batch_size: 128

  - id: evaluate
    op_name: evaluate
    type: aggregate
    save_output: true
    dependencies:
      - build_kg
    params:
      target: triple
      src_namespace: chunk
      tgt_namespace: build_kg
      metrics:
        - accuracy
